### ISSUE TITLE
Algorithm to check facts 

### ISSUE THREAD

**Issue by gsvarma** [gsvarma/Fact_Checker#8]
Hi,

I found this [paper ](https://arxiv.org/pdf/1501.03471v1.pdf) interesting. Please have a look and let me know your opinions. There's a path evaluation function which could be used in our case as confidence value, longer the path evaluation value, less is the confidence value.

**Comment by VarmaHub** [comment]
Please let me know your opinion after reading the paper.

@BurhanOtour @vineete2
